import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import Header from "../components/Header/Header";
import { statuses } from "../utils/themaApi";

import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Learn Lingo",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const randomIndex = Math.floor(Math.random() * statuses.length);

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header status={statuses[randomIndex]} />
        {children}
      </body>
    </html>
  );
}
